### PR TITLE
Getting the project running

### PR DESCRIPTION
**Pull request by asmacdo**

### CODE REVIEW

**Comment by satra** [comment]
@asmacdo - for pydra we rebuilt the latest slurm `adi611/docker-centos7-slurm:23.02.1` and you can ask @adi611 for the dockerfile related to it.

**Comment by asmacdo** [comment]
Thanks @satra we've actually been in touch with the project maintainer, so we can switch to the official build as soon as it's cut.

When that happens I can file an issue over there to use the official build too.

**Comment by yarikoptic** [comment]
FWIW - filed https://github.com/giovtorres/docker-centos7-slurm/issues/53 there

**Comment by asmacdo** [comment]
This isn't being actively developed, I'll close for now

**Pull request closed without merging**
